#!/bin/bash

# Load environment variables
source .env

# Get the current date in YYYY-MM-DD format
CURRENT_DATE=$(date +'%Y-%m-%d')

# Source directory
SOURCE_DIR="/workspace/AWS-Analytics-Pipeline-Viz/dataset/Amazon Sales Dataset.csv"

